services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    image: home-gym-app
    ports:
      - '5011:8000'
    env_file:
      - .env
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    volumes:
      - ./database:/var/www/html/database:Z
      - ./storage:/var/www/html/storage:Z
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
